tech_inheritance:
    model_run_subdict_name: tech
    expected_nesting: ["(inheritance)"]
    data_dimensions: ["techs"]
    end: ""

tech_carrier_specific:
    model_run_subdict_name: tech
    expected_nesting: ["essentials"]
    data_dimensions: ["techs", "carrier_tiers", "carriers"]
    end: "\\.carrier_(out|in|out_2|in_2|out_3|in_3)"
    var_name: carrier
    values_as_dimension: true

tech_primary_carrier_specific:
    model_run_subdict_name: tech
    expected_nesting: ["essentials"]
    data_dimensions: ["techs", "var_name", "carriers"]
    end: "\\.(primary_carrier_out|primary_carrier_in)"
    values_as_dimension: true

tech_essentials:
    model_run_subdict_name: tech
    expected_nesting: ["essentials"]
    data_dimensions: ["techs"]

systemwide_constraints:
    model_run_subdict_name: tech
    expected_nesting: ["constraints"]
    data_dimensions: ["techs"]

carrier_specfic_params:
    model_run_subdict_name: node
    expected_nesting: ["techs", "{0}", "carrier_(out|in|out_2|in_2|out_3|in_3)"]
    data_dimensions: ["nodes", "techs", "var_name", "carrier_tiers", "carriers"]

node_tech_export_carrier_specific:
    model_run_subdict_name: node
    expected_nesting: ["techs", "?{0}"]
    data_dimensions: ["nodes", "techs", "carriers"]
    end: "\\.export_carrier"
    var_name: export_carrier
    values_as_dimension: true

node_tech_params:
    model_run_subdict_name: node
    expected_nesting: ["techs", "?{0}"]
    data_dimensions: ["nodes", "techs"]

node_tech_costs:
    model_run_subdict_name: node
    expected_nesting: ["techs", "costs\\.({0})"]
    data_dimensions: ["nodes", "techs", "costs"]
    var_name_prefix: "cost"

node_link_tech_params:
    model_run_subdict_name: node
    expected_nesting: ["links", "techs", "?{0}"]
    data_dimensions: ["nodes", "node_to", "techs"]
    is_link: true

node_link_tech_costs:
    model_run_subdict_name: node
    expected_nesting: ["links", "techs", "costs\\.({0})"]
    data_dimensions: ["nodes", "node_to", "techs", "costs"]
    is_link: true
    var_name_prefix: "cost"

node_specific_params:
    model_run_subdict_name: node
    expected_nesting: []
    data_dimensions: ["nodes"]
    end: "({0})"

node_coordinates:
    model_run_subdict_name: node
    expected_nesting: ["coordinates"]
    data_dimensions: ["nodes", "coordinates"]
    var_name: "node_coordinates"
