version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - python ./docs/pre_build/generate_math.py
    pre_create_environment:
      - mamba create -n calliope-docs -c conda-forge -c nodefaults python=3.12 --file requirements/docs.txt --file requirements/base.txt
      - mamba activate calliope-docs
    post_create_environment:
      - pip install --no-deps .

mkdocs:
  configuration: mkdocs.yml
