version: 2
conda:
  environment: requirements/base.txt
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_create_environment:
      - mamba install -c gurobi python=3.12 coin-or-cbc --file requirements/dev.txt
      - pip install --no-deps .
      - python -m ipykernel install --user --name calliope_docs_build

mkdocs:
  configuration: mkdocs.yml
