version: 2
conda:
  environment: requirements/base.txt
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_create_environment:
      - mamba install python=3.11 --file requirements/docs.txt
      - pip install --no-deps .


mkdocs:
  configuration: mkdocs.yml
