language: python
sudo: false  # Use container-based infrastructure

matrix:
  include:
  - name: "Python 3.5"
    env: [PYTHON_VERSION="3.5", COVERAGE=FALSE]
  - name: "Python 3.6"
    env: [PYTHON_VERSION="3.6", COVERAGE=TRUE]
  # - name: "Python 3.7"
  #   env: [PYTHON_VERSION="3.7", COVERAGE=TRUE]

before_install:
  - "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;"
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export CONDA_CHANS="conda-forge defaults"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - python utils/conda_create.py requirements/base.yml requirements/travis.yml --python_version=$PYTHON_VERSION --channels $CONDA_CHANS --ignore $CONDA_IGNORE --run
  - source activate calliope
  - pip install --no-cache-dir --verbose -e .

script: make test

after_success:
  - if [ "${COVERAGE}" = "TRUE" ]; then coveralls; fi
