[tool.pytest.ini_options]
minversion = "6.0"
# opts:
# `--dist=loadscope ` - run tests within classes in series
# `--strict-markers` - Raise error on unexpected pytest markers being used (add new markers to `markers` config)
# `-nauto` - parallelise over as many threads as possible (uses pytest-xdist). If debugging (`--pdb`), this will default to one thread.
# `--cov-report=xml --cov-config=pyproject.toml` - coverage report config for when running in tests (uses pytest-cov; call `--cov` in CLI to switch coverage on; `--cov-config` include to avoid bug)
addopts = "-rav --dist=loadscope --strict-markers -nauto --cov-report=xml --cov-config=pyproject.toml -m 'not needs_gurobi_license' --pdbcls=IPython.terminal.debugger:Pdb "

testpaths = ["tests"]

# to mark a test, decorate it with `@pytest.mark.[marker-name]`
markers = ["serial", "time_intensive", "needs_gurobi_license"]
filterwarnings = [
  # https://github.com/pytest-dev/pytest-xdist/issues/825
  "ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning",
  "ignore:(?s).*datetime.datetime.utcfromtimestamp():",
  "ignore:(?s).*Pyarrow will become a required dependency of pandas:DeprecationWarning",
  "ignore:.*The return type of `Dataset.dims` will be changed to return a set of dimension names.*:FutureWarning",
  "ignore:.*Mismatched null-like values None and nan found.*:FutureWarning"
]

[tool.coverage.run]
branch = true
source = ["src/"]

[tool.coverage.html]
directory = "reports/coverage"

[tool.coverage.xml]
output = "reports/coverage/coverage.xml"

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:", "if importlib.util.find_spec('gurobipy')"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
exclude = [".*.egg-info", "requirements/**"]
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["E", "F", "I", "Q", "W", "D", "PT", "UP"]
# line too long; Black will handle these
ignore = ["E501"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

# Ignore `E402` (import violations) and `F401` (unused imports) in all `__init__.py` files
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "D104"]
"*.ipynb" = ["E402"]
"tests/*" = ["D"]
"docs/examples/*" = ["D"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 200
ignore-overlong-task-comments = true

[tool.codespell]
skip = 'tests/*.py,AUTHORS,pixi.lock'
count = ''
quiet-level = 3
ignore-words-list = "socio-economic"  # British english spelling that isn't covered by the inbuilt dictionary

[tool.mypy]
ignore_missing_imports = true
files = "src/"


[project]
name = "calliope"
authors = [
  { name = "Calliope contributors listed in AUTHORS", email = "stefan@pfenninger.org" },
]
maintainers = [
  { name = "Stefan Pfenninger", email = "stefan@pfenninger.org" },
  { name = "Bryn Pickering", email = "17178478+brynpickering@users.noreply.github.com" },
]
description = "A multi-scale energy systems modelling framework."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["energy systems", "optimisation", "mathematical programming"]
license = "Apache-2.0"
license-files = ["LICENSE", "CITATION"]
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]
dynamic = ["version"]
dependencies = [
  "bottleneck >= 1",
  "click >= 8",
  "geographiclib >= 2",
  "ipdb >= 0.13",
  "ipykernel >= 6",
  "jinja2 >= 3",
  "jsonref >= 1.1",
  "jsonschema >= 4",
  "natsort >= 8",
  "netcdf4 >= 1.2",
  "numpy >= 1",
  "pandas >= 2.1.3",
  "pyomo >= 6.8.2",
  "pyparsing >= 3.2",
  "ruamel.yaml >= 0.18",
  "typing-extensions >= 4",
  "xarray >= 2026.4",
  "pydantic >= 2.11.4",
]

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.sdist]
only-include = ["src", "LICENSE", "CITATION", "AUTHORS", "README.md"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/calliope/_version.py"

[project.scripts]
calliope = "calliope.cli:cli"

[project.urls]
website = "https://www.callio.pe/"
repository = "https://github.com/calliope-project/calliope"
documentation = "https://calliope.readthedocs.io"
changelog = "https://github.com/calliope-project/calliope/changelog.rst"

[tool.pixi.workspace]
channels = ["conda-forge", "gurobi"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[tool.pixi.dependencies]
libnetcdf = "*"
gurobi = "*"
uv = "*"
glpk = "==5.0"
coin-or-cbc = "*"
rich = ">=14.0.0"

[tool.pixi.pypi-dependencies]
calliope = { path = ".", editable = true}

[tool.pixi.feature.docs.dependencies]
jsonschema2md = ">=1"
mkdocs = ">=1.5"
mkdocs-click = ">=0.6"
mkdocs-jupyter = ">=0.25"
mkdocs-macros-plugin = ">=1.0"
mkdocs-material = ">=9.5"
mkdocstrings-python = ">=1.7"
plotly = ">=5"

[tool.pixi.feature.dev.dependencies]
identify = ">=2.5.24"
mypy = ">=1.13.0"
pandas-stubs = "*"
pre-commit = ">=3"
pytest = ">=8"
pytest-cov = ">=4"
pytest-order = ">=1"
pytest-xdist = ">=3"
platformdirs = ">=4.11.0"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.py314.dependencies]
python = "3.14.*"

[tool.pixi.tasks]
init-dev-env = { cmd = "pre-commit install", default-environment = "dev" }
test = { cmd = "pytest --no-cov", default-environment = "dev", depends-on = ["init-dev-env"] }
test-ci = { cmd = "pytest --no-cov -m 'not time_intensive' -m 'not needs_gurobi_license'", default-environment = "dev", depends-on = ["init-dev-env"]  }
test-cov = { cmd = "pytest --cov", default-environment = "dev", depends-on = ["init-dev-env"] }
docs-build = { cmd = "PLOTLY_RENDERER=notebook mkdocs build", default-environment = "docs" }
docs-serve = { cmd = "PLOTLY_RENDERER=notebook mkdocs serve", default-environment = "docs" }

[tool.pixi.environments]
default = { solve-group = "py314" }
dev = { features = ["dev"], solve-group = "py314" }
docs = { features = ["py312", "docs"], solve-group = "py312" }
py311 = { features = ["py311", "dev"]}
py312 = { features = ["py312", "dev"], solve-group = "py312" }
py313 = { features = ["py313", "dev"]}
py314 = { features = ["py314", "dev"], solve-group = "py314" }

[tool.pixi.package]
name = { workspace = true }

[tool.pixi.package.build.backend]
channels = ["https://prefix.dev/conda-forge"]
name = "pixi-build-python"
version = "0.*"

[tool.pixi.package.build.config]
ignore-pypi-mapping = false  # Enable automatic PyPI-to-conda mapping
