name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck
    - click
    - coverage >= 4.4
    - codecov
    - glpk=4.61
    - hdf5
    - ipdb
    - ipython
    - jinja2
    - libnetcdf
    - natsort
    - netcdf4
    - numexpr
    - numpy
    - pandas=0.25
    - plotly<4.0
    - pre-commit
    - pyomo=5.6
    - pytest-cov
    - pytest-xdist  # pytest distributed testing plugin
    - pytest=5.2  # 5.3 fails with KeyError: '__name__' when collecting items
    - ruamel.yaml=0.16
    - scikit-learn
    - xarray=0.14
