name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck
    - click
    - coverage >= 4.4
    - codecov
    - glpk=4.61
    - hdf5
    - ipdb
    - ipython
    - libnetcdf
    - natsort
    - netcdf4
    - numpy
    - pandas=1.1
    - pre-commit
    - pyomo=5.7
    - pytest-cov
    - pytest-xdist  # pytest distributed testing plugin
    - pytest=5.2  # 5.3 fails with KeyError: '__name__' when collecting items
    - ruamel.yaml=0.16
    - scikit-learn>=0.22,<0.24  # 0.24 leads to failed clustering, due to some API change
    - xarray=0.16
