name: calliope

channels:
    - conda-forge

dependencies:
    - coverage >= 4.4
    - codecov
    - glpk=4.61
    - hdf5
    - libnetcdf
    - pre-commit
    - pytest-cov
    - pytest-xdist  # pytest distributed testing plugin
    - pytest

