name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck < 2
    - coverage >= 4.4
    - codecov
    - glpk = 5.0
    - hdf5 < 2
    - libnetcdf < 4.9
    - pre-commit
    - pytest-cov
    - pytest-xdist  # pytest distributed testing plugin
    - pytest

