name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck
    - click
    - coverage >= 4.4
    - codecov
    - glpk=4.61
    - hdf5
    - ipdb
    - ipython
    - libnetcdf
    - natsort
    - netcdf4
    - numpy>=1.15,<1.20
    - pandas=1.2
    - pre-commit
    - pyomo=6.0
    - pytest-cov
    - pytest-xdist  # pytest distributed testing plugin
    - pytest
    - ruamel.yaml=0.16
    - scikit-learn>=0.22,<0.24  # 0.24 leads to failed clustering, due to some API change
    - xarray=0.17
