name: calliope

channels:
    - conda-forge
    - anaconda

dependencies:
    - python=3.6
    - basemap
    - bottleneck
    - click
    - descartes  # For analysis_utils.plot_shapefile_polys
    - glpk=4.61
    - hdf5
    - libnetcdf
    - matplotlib=2
    - netcdf4
    - networkx
    - numexpr
    - numpy=1.12.1
    - pandas=0.19
    - pyomo=5.2
    - pytest
    - pytest-cov
    - pyyaml
    - scipy
    - seaborn  # Used in the example notebook
    - shapely  # For analysis_utils.plot_shapefile_polys
    - xarray=0.9.5
