name: calliope

channels:
    - anaconda
    - conda-forge

dependencies:
    - python=3.5
    - basemap
    - bottleneck
    - click
    - descartes  # For analysis_utils.plot_shapefile_polys
    - glpk=4.59  # 4.60 causes problems with current version of Pyomo
    - hdf5
    - libnetcdf
    - matplotlib=1.5.1
    - pyqt=4.11.4  # Else conda installs PyQt5 and that breaks matplotlib
    - netcdf4
    - networkx
    - numexpr
    - numpy=1.11.1
    - pandas=0.19.0
    - pyomo=4.4.1
    - pytest
    - pytest-cov
    - pyyaml
    - scipy
    - seaborn  # Used in the example notebook
    - shapely  # For analysis_utils.plot_shapefile_polys
    - xarray=0.8.2
