# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema#

$schema: https://json-schema.org/draft/2020-12/schema#
title: Model definition schema
description: All options available to configure a Calliope model.
type: object
additionalProperties: false
$defs:
  unIndexedParamVal:
    type: [string, boolean, number, "null"]
    description: zero-dimensional (i.e., un-indexed) parameter.

  IndexedParamIndex:
    description: >-
      Model dimension members to apply the parameter value(s) to.
      If an array of arrays, sub-arrays must have same length as number of `dims`.
    oneOf:
      - type: [string, integer, number]
      - type: array
        uniqueItems: true
        minItems: 1
        items:
          oneOf:
            - type: array
              minItems: 1
              items:
                type: [string, integer, number]
            - type: [string, integer, number]

  IndexedParamData:
    description: >-
      parameter value(s).
      If data is one value, will be applied to all dimension members.
      If a list, must be same length as the index array.
    oneOf:
      - type: [string, boolean, integer, number, "null"]
      - type: array
        minItems: 1
        items:
          type: [string, boolean, integer, number, "null"]

  IndexedParam:
    type: object
    description: Indexed parameter.
    additionalProperties: false
    required: ["data", "index", "dims"]
    properties:
      data:
        $ref: "#/$defs/IndexedParamData"
      index:
        $ref: "#/$defs/IndexedParamIndex"
      dims:
        description: >-
          Model dimension(s) over which the parameter is indexed.
          Must be same length as the sub-arrays of `index` (if `indexed` does not have any sub-arrays or is simply a single value, `dims` must be of length 1).
        oneOf:
          - type: string
          - type: array
            uniqueItems: true
            minItems: 1
            items:
              type: string
  TechDims:
    dims:
      description: >-
        Model dimension(s) over which the parameter is indexed.
        Must be same length as the sub-arrays of `index` (if `indexed` does not have any sub-arrays or is simply a single value, `dims` must be of length 1).
        Cannot include `techs` or `nodes` as these will be added automatically in preprocessing.
      oneOf:
        - type: string
        - type: array
          uniqueItems: true
          minItems: 1
          items:
            type: string
            not:
              enum: [techs, nodes]

  TechCostDims:
    description: >-
      Model dimension(s) over which the parameter is indexed.
      Must be same length as the sub-arrays of `index` (if `indexed` does not have any sub-arrays or is simply a single value, `dims` must be of length 1).
      Cannot include `techs` or `nodes` as these will be added automatically in preprocessing.
      Must include `costs` as the string or as an element of the array.
    oneOf:
      - type: string
        enum: [costs]
      - type: array
        uniqueItems: true
        minItems: 1
        items:
          type: string
          not:
            enum: [techs, nodes]
        contains:
          const: costs

  TechParamNullNumber:
    oneOf:
      - type: ["null", number]
      - type: object
        description: Indexed tech-level parameter with null/numeric dtype.
        additionalProperties: false
        required: ["data", "index", "dims"]
        properties:
          data:
            description: >-
              parameter value(s).
              If data is one value, will be applied to all dimension members.
              If a list, must be same length as the index array.
            oneOf:
              - type: "null"
              - type: number
                minimum: 0
              - type: array
                minItems: 1
                items:
                  oneOf:
                    - type: "null"
                    - type: number
                      minimum: 0
          index:
            $ref: "#/$defs/IndexedParamIndex"
          dims:
            $ref: "#/$defs/TechDims"

  TechCostNullNumber:
    oneOf:
      - type: ["null", number]
        x-type: float
      - type: object
        description: Indexed tech-level cost.
        additionalProperties: false
        required: ["data", "index", "dims"]
        properties:
          data:
            description: >-
              parameter value(s).
              If data is one value, will be applied to all dimension members.
              If a list, must be same length as the index array.
            oneOf:
              - type: "null"
              - type: number
              - type: array
                minItems: 1
                items:
                  oneOf:
                    - type: "null"
                    - type: number
          index:
            $ref: "#/$defs/IndexedParamIndex"
          dims:
            $ref: "#/$defs/TechCostDims"

  ActiveDef:
    type: boolean
    title: Activated component.
    description:
      If false, the model component (tech/node/link) will not make its way through to preprocessing.
      If a node, links between this node and others, via transmission technologies, will also be deactivated.
    default: true

properties:
  parameters:
    type: object
    description: Calliope model arbitrary parameter definitions.
    additionalProperties: false
    patternProperties:
      '^[^_^\d][\w]*$':
        oneOf:
          - $ref: "#/$defs/unIndexedParamVal"
          - $ref: "#/$defs/IndexedParam"

  techs:
    type: object
    description: Calliope model technology definitions.
    additionalProperties: false
    patternProperties:
      '^[^_^\d][\w]*$':
        type: object
        description: A named technology.
        allOf:
          - required: ["base_tech"]
          - oneOf:
              - required: ["base_tech", "carrier_in", "carrier_out"]
                not:
                  required: ["link_to", "link_from"]
                properties:
                  base_tech: {const: conversion}
              - required: ["base_tech", "carrier_in"]
                not:
                  required: ["carrier_out", "link_to", "link_from"]
                properties:
                  base_tech: {const: demand}

              - required: ["base_tech", "carrier_in", "carrier_out"]
                not:
                  required: ["link_to", "link_from"]
                properties:
                  base_tech: {const: storage}

              - required: ["base_tech", "carrier_out"]
                not:
                  required: ["carrier_in", "link_to", "link_from"]
                properties:
                  base_tech: {const: supply}

              - required:
                  [
                    "base_tech",
                    "link_from",
                    "link_to",
                    "carrier_in",
                    "carrier_out",
                  ]
                properties:
                  base_tech: {const: transmission}
                  from:
                    title: Starting node.
                    description: The resulting link technology will have `flow_out` == `import` and `flow_in` == `export` at this node.
                    type: string
                  to:
                    title: Ending node.
                    description: The resulting link technology will have `flow_out` == `import` and `flow_in` == `export` at this node.
                    type: string

        patternProperties: &pattern_def
          '^(cost_[\w]+)$':
            $ref: "#/$defs/TechCostNullNumber"
        unevaluatedProperties: &uneval_def
          oneOf:
            - $ref: "#/$defs/unIndexedParamVal"
            - type: object
              description: Indexed tech-level parameter with any dtype.
              additionalProperties: false
              required: ["data", "index", "dims"]
              properties:
                data:
                  $ref: "#/$defs/IndexedParamData"
                index:
                  $ref: "#/$defs/IndexedParamIndex"
                dims:
                  $ref: "#/$defs/TechDims"

        properties:
          active:
            $ref: "#/$defs/ActiveDef"

          base_tech:
            type: string
            x-type: str
            enum: [demand, supply, conversion, storage, transmission]
            title: Abstract base technology name.
            description: Should be the name of one of the abstract base classes, from which some initial parameter defaults will be derived and with which certain base math will be triggered.

          color:
            type: ["null", string]
            default: .nan
            description: Color that can be used when plotting results.
            x-type: str

          carrier_in:
            description: >-
              Carrier(s) consumed by this technology.
              Only `transmission`, `conversion`, `storage`, and `demand` technologies can define this parameter
            x-type: float
            oneOf:
              - type: string
              - type: array
                uniqueItems: true
                minItems: 2
                items:
                  type: string

          carrier_out:
            description: >-
              Carrier(s) produced by this technology.
              Only `transmission`, `conversion`, `storage`, and `supply` technologies can define this parameter
            x-type: float
            oneOf:
              - type: string
              - type: array
                uniqueItems: true
                minItems: 2
                items:
                  type: string

          carrier_export:
            description: >-
              Carrier(s) produced by this technology that can be exported out of the system boundaries without having to go to a pre-defined `sink` (i.e., via a `demand` technology).
              Must be a subset of `carrier_out`.
            x-type: float
            oneOf:
              - type: string
              - type: array
                uniqueItems: true
                minItems: 2

          name:
            type: ["null", string]
            x-resample_method: first
            x-type: str
            title: Technology long-name.
            description: Long name of technology, which can be used in post-processing (e.g., plotting).
            default: .nan

          cap_method:
            type: string
            default: continuous
            x-resample_method: first
            x-type: str
            title: Capacity method switch.
            description: One of 'continuous' (LP model) or 'integer' (integer/binary unit capacity).
            enum: [continuous, integer]

          sink_unit:
            type: string
            default: absolute
            x-resample_method: first
            x-type: str
            title: Sink unit
            description: >-
              Sets the unit of `Sink` to either `absolute` (unit: `energy`), `per_area` (unit: `energy/area`), or `per_cap` (unit: `energy/power`).
              `per_area` uses the `area_use` decision variable to scale the sink while `per_cap` uses the `flow_cap` decision variable.
            enum: [absolute, per_area, per_cap]

          source_unit:
            type: string
            default: absolute
            x-resample_method: first
            x-type: str
            title: Source unit
            description: >-
              Sets the unit of `Source` to either `absolute` (unit: `energy`), `per_area` (unit: `energy/area`), or `per_cap` (unit: `energy/power`).
              `per_area` uses the `area_use` decision variable to scale the source while `per_cap` uses the `flow_cap` decision variable.
            enum: [absolute, per_area, per_cap]

  nodes:
    type: object
    description: Calliope model node definitions.
    additionalProperties: false
    patternProperties:
      '^[^_^\d][\w]*$':
        type: object
        title: A named node.
        dependentRequired": {latitude: ["longitude"], longitude: ["latitude"]}

        patternProperties: *pattern_def
        unevaluatedProperties: *uneval_def
        properties:
          active:
            $ref: "#/$defs/ActiveDef"
          latitude:
            type: number
            x-type: float
            title: Latitude (WGS84 / EPSG4326).
            minimum: -90
            maximum: 90
          longitude:
            type: number
            x-type: float
            title: Longitude (WGS84 / EPSG4326).
            minimum: -180
            maximum: 180
