fail:
  - where: not base_tech
    message: An abstract `base_tech` must be defined for every technology at every node.

  - where: not base_tech=transmission and (distance or flow_in_eff_per_distance or flow_out_eff_per_distance or cost_flow_cap_per_distance or cost_purchase_per_distance)
    message: Only transmission technologies can define `distance` or `..._per_distance` parameters.

  - where: cost_flow_cap<0 AND not flow_cap_max
    message: Cannot have a negative `cost_flow_cap` as there is an unset corresponding `flow_cap_max` constraint

  - where: cost_storage_cap<0 AND not storage_cap_max
    message: Cannot have a negative `cost_storage_cap` as there is an unset corresponding `storage_cap_max` constraint

  - where: cost_area_use<0 AND not area_use_max
    message: Cannot have a negative `cost_area_use` as there is an unset corresponding `area_use_max` constraint

  - where: cost_source_cap<0 AND not source_use_max
    message: Cannot have a negative `cost_source_cap` as there is an unset corresponding `source_use_max` constraint

  - where: source_use_equals=inf or sink_use_equals=inf
    message: "Cannot include infinite values in `source_use_equals`/`sink_use_equals`"

  - where: (any(latitude, over=nodes) or any(longitude, over=nodes)) and not (latitude or longitude)
    message: "Must define node latitude and longitude for _all_ nodes or _no_ nodes."

  - where: carrier_export and not any(carrier_out, over=nodes)
    message: "Export carriers must be one of the technology outflow carriers."

  - where: storage_initial<0 OR storage_initial>1
    message: "storage_initial is a fraction, requiring values within the interval [0, 1]."

  - where: integer_dispatch=True AND NOT cap_method=integer
    message: Cannot use the integer `integer_dispatch` unless the technology is using an integer unit capacities (`cap_method=integer`).

  - where: (flow_cap_max OR flow_cap_min) AND flow_cap_per_unit
    message: Cannot define both `flow_cap_per_unit` and `flow_cap_max`/`flow_cap_min`

  - where: (storage_cap_max OR storage_cap_min) AND storage_cap_per_unit
    message: Cannot define both `storage_cap_per_unit` and `storage_cap_max`/`storage_cap_min`

warn:
  - where: cyclic_storage=True AND (base_tech=storage OR include_storage=True) AND config.mode=operate
    message: >-
      Cyclic storage should be switched off in operate mode.
      Since the parameter defaults to True, make sure you explicitly set `cyclic_storage: false` for all your technologies with storage.
