name: Bug Report
description: Report a bug that leads to Calliope not working as expected.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
      value: "Something unexpected happened!"
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of Calliope are you using?
      placeholder: v0.1.0
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: false
