# Copyright (C) since 2013 Calliope contributors listed in AUTHORS.
# Licensed under the Apache 2.0 License (see LICENSE file).

"""
generate_custom_math_examples.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Generates a markdown file listing all custom math examples.

"""

from io import StringIO
from pathlib import Path

import mkdocs_gen_files
import ruamel.yaml

CUSTOM_MATH_PATH = "docs/custom_math"
CUSTOM_MATH_DOC_FILE = "_autogenerated/custom_math_examples.md"

MD_BASE_STRING = """

This section lists a range of examples built using custom math functionality.

!!! note

    These constraints are tested in a limited fashion and it is up to you, the user, to make sure you understand the maths when you apply them to your own model!

"""

MD_EXAMPLE_STRING = """
## {title}

{description}

[:fontawesome-solid-download: Download the YAML example]({yaml_file_path})

```yaml
{example_yaml}
```
"""


def generate_custom_math_examples():
    custom_math_dir = Path(CUSTOM_MATH_PATH)

    md_string = MD_BASE_STRING

    for yaml_file in sorted(custom_math_dir.glob("*.yaml")):
        md_string = md_string + process_file(yaml_file)

    with mkdocs_gen_files.open(CUSTOM_MATH_DOC_FILE, "w") as f:
        f.write(md_string)


def process_file(path):
    text = path.read_text()

    comment_, yaml_ = text.split("# ---", 1)

    comment_yaml_block = "\n".join(i.removeprefix("#") for i in comment_.split("\n"))

    yaml = ruamel.yaml.YAML(typ="safe")
    comment_yaml = yaml.load(StringIO(comment_yaml_block))

    title = comment_yaml.get("title", "")
    description = comment_yaml.get("description", "")

    example_yaml = "\n".join(i for i in yaml_.split("\n"))

    return MD_EXAMPLE_STRING.format(
        title=title,
        description=description,
        yaml_file_path=str(path).replace("docs/", "../"),
        example_yaml=example_yaml,
    )


generate_custom_math_examples()
