name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck
    - click=6  # v7.0 changes '_' to '-' in subcommands
    - glpk=4.61
    - hdf5
    - ipython
    - ipdb
    - jinja2
    - libnetcdf
    - natsort
    - netcdf4
    - numexpr
    - numpy
    - pandas<0.24
    - plotly<4.0
    - pyomo<5.5
    - pytest
    - pytest-cov
    - ruamel.yaml<0.16
    - scikit-learn<0.21
    - xarray<0.11
