name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck
    - click
    - cufflinks-py=0.12.1
    - glpk=4.61
    - hdf5
    - ipython
    - ipdb
    - jinja2
    - libnetcdf
    - natsort
    - netcdf4
    - numexpr
    - numpy=1.14.1
    - pandas=0.22
    - plotly=2.5
    - pyomo=5.4.3
    - pytest
    - pytest-cov
    - ruamel.yaml<0.16
    - scikit-learn=0.19.1
    - xarray=0.10.8
    - pip:
        - "git+https://github.com/calliope-project/calliope.git"
