name: Markdown link check

on:
  schedule:  # runs every monday at 9 am
    - cron: "0 9 * * 1"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15