name: Publish to PyPI

on:
  release:
    types: [released]

jobs: # separate build and publish to restrict id-token write permissions to fewer steps
  pypi-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build
        run: uv build
      # Persist artifacts for the next jobs
      - uses: actions/upload-artifact@v7
        with:
          name: dists
          path: dist/

  pypi-publish:

    needs: [pypi-build]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Download build artifacts from the build job
        uses: actions/download-artifact@v8
        with:
          name: dists
          path: dist/
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Publish
        run: uv publish
