name: Publish to PyPI

on:
  release:
    types: [released]

jobs:
  pip-publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: Download built package from pre-release workflow artifacts
        uses: dawidd6/action-download-artifact@v21
        with:
          name: dist
          workflow: pre-release.yml
          path: dist/
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Publish
        run: uv publish
